import { envBool } from './env.js';

export const OFFICIAL_POLICY_SOURCES = [
  {
    id: 'bokjiro-central-welfare',
    label: '복지로 중앙부처 복지서비스',
    priority: 100,
    strategy: 'official_api',
    apiBaseEnv: 'BOKJIRO_CENTRAL_API_URL',
    detailUrlEnv: 'BOKJIRO_CENTRAL_DETAIL_API_URL',
    apiKeyEnv: 'BOKJIRO_CENTRAL_SERVICE_KEY',
    fallbackApiKeyEnv: 'BOKJIRO_SERVICE_KEY',
    authParam: 'serviceKey',
    enabledEnv: 'ENABLE_BOKJIRO_CENTRAL',
    defaultEnabled: true,
    defaultParams: { numOfRows: 50, pageNo: 1 },
    pagination: { pageParam: 'pageNo', sizeParam: 'numOfRows', size: 50 },
    detail: {
      idKeys: ['wlfareInfoId', 'servId', 'serviceId', 'id', '서비스ID'],
      param: 'wlfareInfoId',
      maxDetails: 25,
    },
    note: '공식 API가 제공하는 중앙부처 복지서비스 목록과 상세 데이터를 우선 수집합니다.',
  },
  {
    id: 'bokjiro-local-welfare',
    label: '복지로 지자체 복지서비스',
    priority: 90,
    strategy: 'official_api',
    apiBaseEnv: 'BOKJIRO_LOCAL_API_URL',
    detailUrlEnv: 'BOKJIRO_LOCAL_DETAIL_API_URL',
    apiKeyEnv: 'BOKJIRO_LOCAL_SERVICE_KEY',
    fallbackApiKeyEnv: 'BOKJIRO_SERVICE_KEY',
    authParam: 'serviceKey',
    enabledEnv: 'ENABLE_BOKJIRO_LOCAL',
    defaultEnabled: true,
    defaultParams: { numOfRows: 50, pageNo: 1 },
    pagination: { pageParam: 'pageNo', sizeParam: 'numOfRows', size: 50 },
    detail: {
      idKeys: ['wlfareInfoId', 'servId', 'serviceId', 'id', '서비스ID'],
      param: 'wlfareInfoId',
      maxDetails: 25,
    },
    note: '지역별 복지서비스를 수집해 중앙 정책과 분리 저장합니다.',
  },
  {
    id: 'gov24-benefits',
    label: '정부24/공공서비스 혜택 정보',
    priority: 80,
    strategy: 'official_api',
    apiBaseEnv: 'GOV24_BENEFIT_API_URL',
    detailUrlEnv: 'GOV24_DETAIL_API_URL',
    supportConditionsUrlEnv: 'GOV24_SUPPORT_CONDITIONS_API_URL',
    apiKeyEnv: 'GOV24_SERVICE_KEY',
    authParam: 'serviceKey',
    enabledEnv: 'ENABLE_GOV24_BENEFITS',
    defaultEnabled: true,
    defaultParams: { page: 1, perPage: 50, returnType: 'JSON' },
    pagination: { pageParam: 'page', sizeParam: 'perPage', size: 50 },
    detail: {
      idKeys: ['serviceId', 'svcId', 'servId', '서비스ID', 'id'],
      param: 'serviceId',
      maxDetails: 25,
    },
    support: {
      idKeys: ['serviceId', 'svcId', 'servId', '서비스ID', 'id'],
      param: 'serviceId',
      maxDetails: 25,
    },
    note: '정부·지자체·공공기관 혜택 정보를 정책 후보로 수집합니다.',
  },

  {
    id: 'law-current-welfare-acts',
    label: '국가법령정보센터 복지 관련 현행법령',
    priority: 78,
    strategy: 'official_api',
    kind: 'legal_basis',
    apiBaseEnv: 'LAW_SEARCH_API_URL',
    detailUrlEnv: 'LAW_SERVICE_API_URL',
    apiKeyEnv: 'LAW_OPEN_API_OC',
    authParam: 'OC',
    enabledEnv: 'ENABLE_LAW_WELFARE_ACTS',
    defaultEnabled: true,
    defaultParams: { target: 'law', type: 'XML', page: 1, display: 20 },
    queryEnv: 'LAW_POLICY_QUERIES',
    defaultQueries: ['복지', '기초생활보장', '청년', '주거급여', '고용보험'],
    queryParam: 'query',
    pagination: { pageParam: 'page', sizeParam: 'display', size: 20 },
    detail: {
      idKeys: ['법령일련번호', 'MST', 'mst', '법령ID', 'lawId', 'ID', 'id'],
      param: 'MST',
      maxDetails: 20,
    },
    note: '국가법령정보센터 공동활용 Open API에서 복지·주거·고용 관련 현행 법령 목록과 본문을 수집해 정책 판단 근거로 저장합니다.',
  },
  {
    id: 'youth-policy',
    label: '온통청년 청년정책',
    priority: 75,
    strategy: 'official_api',
    apiBaseEnv: 'YOUTH_POLICY_API_URL',
    apiKeyEnv: 'YOUTH_POLICY_API_KEY',
    authParam: 'openApiVlak',
    enabledEnv: 'ENABLE_YOUTH_POLICY',
    defaultEnabled: false,
    defaultParams: { display: 50, pageIndex: 1 },
    pagination: { pageParam: 'pageIndex', sizeParam: 'display', size: 50 },
    detail: {
      idKeys: ['plcyNo', 'bizId', 'policyId', 'id', '정책ID'],
      param: 'plcyNo',
      maxDetails: 25,
    },
    note: '청년정책 정보를 보조 수집합니다. 발급받은 온통청년 API 키가 필요합니다.',
  },
  {
    id: 'myhome-public-housing-notice',
    label: '마이홈 공공주택 모집공고',
    priority: 60,
    strategy: 'official_api',
    apiBaseEnv: 'MYHOME_PUBLIC_HOUSING_NOTICE_API_URL',
    apiKeyEnv: 'MYHOME_SERVICE_KEY',
    authParam: 'serviceKey',
    enabledEnv: 'ENABLE_MYHOME_PUBLIC_HOUSING_NOTICE',
    defaultEnabled: false,
    defaultParams: { _type: 'json', numOfRows: 50, pageNo: 1 },
    pagination: { pageParam: 'pageNo', sizeParam: 'numOfRows', size: 50 },
    note: '주거지원·공공주택 공고를 수집합니다. data.go.kr 소개 페이지가 아닌 실제 호출 엔드포인트를 넣어야 합니다.',
  },
  {
    id: 'myhome-rental-housing-complex',
    label: '마이홈 공공임대주택 단지정보',
    priority: 55,
    strategy: 'official_api',
    apiBaseEnv: 'MYHOME_RENTAL_HOUSING_COMPLEX_API_URL',
    apiKeyEnv: 'MYHOME_SERVICE_KEY',
    authParam: 'serviceKey',
    enabledEnv: 'ENABLE_MYHOME_RENTAL_HOUSING_COMPLEX',
    defaultEnabled: false,
    defaultParams: { _type: 'json', numOfRows: 50, pageNo: 1 },
    pagination: { pageParam: 'pageNo', sizeParam: 'numOfRows', size: 50 },
    note: '공공임대주택 단지 정보를 수집합니다. 실제 API 호출 URL 확인 후 활성화하세요.',
  },
  {
    id: 'myhome-waiting-list',
    label: '마이홈 예비입주자 대기현황',
    priority: 50,
    strategy: 'official_api',
    apiBaseEnv: 'MYHOME_WAITING_LIST_API_URL',
    apiKeyEnv: 'MYHOME_SERVICE_KEY',
    authParam: 'serviceKey',
    enabledEnv: 'ENABLE_MYHOME_WAITING_LIST',
    defaultEnabled: false,
    defaultParams: { _type: 'json', numOfRows: 50, pageNo: 1 },
    pagination: { pageParam: 'pageNo', sizeParam: 'numOfRows', size: 50 },
    note: '예비입주자 대기현황을 보조 수집합니다. 실제 API 호출 URL 확인 후 활성화하세요.',
  },
  {
    id: 'worknet-jobs',
    label: '워크넷 고용·채용 보조 데이터',
    priority: 45,
    strategy: 'official_api',
    apiBaseEnv: 'WORKNET_JOB_API_URL',
    apiKeyEnv: 'WORKNET_SERVICE_KEY',
    authParam: 'authKey',
    enabledEnv: 'ENABLE_WORKNET_JOBS',
    defaultEnabled: false,
    defaultParams: { returnType: 'XML', startPage: 1, display: 50 },
    pagination: { pageParam: 'startPage', sizeParam: 'display', size: 50 },
    note: '복지 정책은 아니지만 고용·구직 전환 판단을 보조하는 데이터로 활용합니다.',
  },
  {
    id: 'local-notice-allowlist',
    label: '허용된 지자체 공고문 보조 수집',
    priority: 30,
    strategy: 'crawl_allowlist',
    urlListEnv: 'LOCAL_NOTICE_URLS',
    enabledEnv: 'ENABLE_LOCAL_NOTICE_CRAWLER',
    defaultEnabled: false,
    note: 'API 반영이 늦은 지자체 공고만 allowlist URL에서 보조 수집합니다.',
  },
];

export function enabledSources(env = process.env) {
  return OFFICIAL_POLICY_SOURCES.filter((source) => envBool(source.enabledEnv, source.defaultEnabled, env));
}